/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AddOneImport } from './routes/addOne'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const AddOneRoute = AddOneImport.update({
  id: '/addOne',
  path: '/addOne',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/addOne': {
      id: '/addOne'
      path: '/addOne'
      fullPath: '/addOne'
      preLoaderRoute: typeof AddOneImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addOne': typeof AddOneRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addOne': typeof AddOneRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/addOne': typeof AddOneRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/addOne'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addOne'
  id: '__root__' | '/' | '/addOne'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddOneRoute: typeof AddOneRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddOneRoute: AddOneRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/addOne"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/addOne": {
      "filePath": "addOne.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
